version: "3.0"
services:
  core:
    container_name: core
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - MONGO_DB_URL=${MONGO_DB_URL:-mongodb://mongo:27017/?compressors=zlib&gssapiServiceName=mongodb}

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - backend

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch
    command: ./meilisearch --master-key=${MEILISEARCH_DB_API_KEY:-masterKey} --no-analytics=true
    networks:
      - backend

  mongo:
    container_name: mongo
    image: mvertes/alpine-mongo
    networks:
      - backend
    ports:
      - "${MONGO_DB_PORT:-27017}:${MONGO_DB_PORT:-27017}"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME:-taco-rocket}

networks:
  backend:
