version: '3.0'
services:
  core:
    container_name: core
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - backend
    volumes:
      - ./:/usr/src/app
    ports:
      - '${PORT:-8000}:${PORT:-8000}'
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    networks:
      - backend
    image: mongo
    ports:
      - '${DB_PORT:-27017}:${DB_PORT:-27017}'
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-taco-rocket}

networks:
  backend:

volumes:
  core:
  mongodb:
